# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: aiovantage
site_url: https://aiovantage.readthedocs.io
repo_url: https://github.com/loopj/aiovantage
repo_name: "loopj/aiovantage"
edit_uri: "blob/main/docs"
watch: [mkdocs.yml, README.md, CONTRIBUTING.md, src/aiovantage]

nav:
  - Overview: index.md
  - API Reference: reference
  - Contributing: contributing.md
  - License: license.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

theme:
  name: material

  icon:
    logo: material/alpha-v-box-outline
  favicon: images/favicon.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: "Switch to light mode"

  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.follow

plugins:
  - search
  - api-autonav:
      modules: ["src/aiovantage"]
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]

          options:
            # General
            show_source: false

            # Headings
            heading_level: 1
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true

            # Members
            members_order: source
            filters: ["!^_"]
            summary: true

            # Docstrings
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            merge_init_into_class: true
            scoped_crossrefs: true

            # Signatures
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.snippets:
      dedent_subsections: true
  - toc:
      permalink: true

extra_css:
  - stylesheets/mkdocstrings.css
