---
name: "Feature request"
description: "Suggest an idea for this project"
labels: "Feature+Request"
body:
- type: markdown
  attributes:
    value: Before you open a new feature request, search through the existing feature requests to see if others have had the same idea.
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
        required: true
      - label: This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).
        required: true

- type: textarea
  attributes:
    label: "Describe the feature you'd like"
    description: "A clear and concise description of what you want to happen, and what problem is solves."
  validations:
    required: true

- type: textarea
  attributes:
    label: "Additional context"
    description: "Add any other context or screenshots about the feature request here."
  validations:
    required: false
