"""Vantage object types."""

# ruff: noqa: F403

# Make all objects available in the aiovantage.objects namespace
from .system_object import *
from .system_object.button import *
from .system_object.gmem import *
from .system_object.location_object import *
from .system_object.location_object.area import *
from .system_object.location_object.blind import *
from .system_object.location_object.blind_group import *
from .system_object.location_object.custom_device import *
from .system_object.location_object.custom_device.child_device import *
from .system_object.location_object.custom_device.child_device.somfy_rs_485_group_child import *
from .system_object.location_object.custom_device.child_device.somfy_rs_485_shade_child import *
from .system_object.location_object.custom_device.child_device.somfy_urtsi_2_group_child import *
from .system_object.location_object.custom_device.child_device.somfy_urtsi_2_shade_child import *
from .system_object.location_object.custom_device.parent_device import *
from .system_object.location_object.custom_device.parent_device.port_device import *
from .system_object.location_object.custom_device.parent_device.port_device.somfy_rs_485_sdn_20_port import *
from .system_object.location_object.custom_device.parent_device.port_device.somfy_urtsi_2_port import *
from .system_object.location_object.custom_device.parent_device.port_device.vantage_dmx_gateway import *
from .system_object.location_object.dry_contact import *
from .system_object.location_object.load import *
from .system_object.location_object.load_group import *
from .system_object.location_object.relay_blind import *
from .system_object.location_object.sensor import *
from .system_object.location_object.sensor.anemo_sensor import *
from .system_object.location_object.sensor.light_sensor import *
from .system_object.location_object.sensor.omni_sensor import *
from .system_object.location_object.sensor.temperature import *
from .system_object.location_object.station_object import *
from .system_object.location_object.station_object.contact_input import *
from .system_object.location_object.station_object.din_station import *
from .system_object.location_object.station_object.din_station.din_contact_input import *
from .system_object.location_object.station_object.din_station.din_high_voltage_relay_station import *
from .system_object.location_object.station_object.din_station.din_low_voltage_relay_station import *
from .system_object.location_object.station_object.eq_ctrl import *
from .system_object.location_object.station_object.eq_ux import *
from .system_object.location_object.station_object.high_voltage_relay_station import *
from .system_object.location_object.station_object.keypad import *
from .system_object.location_object.station_object.keypad.dimmer import *
from .system_object.location_object.station_object.keypad.dual_relay_station import *
from .system_object.location_object.station_object.keypad.scene_point_relay import *
from .system_object.location_object.station_object.low_voltage_relay_station import *
from .system_object.location_object.station_object.qis_blind import *
from .system_object.location_object.station_object.qube_blind import *
from .system_object.location_object.station_object.rs232_station import *
from .system_object.location_object.station_object.rs485_station import *
from .system_object.location_object.station_object.thermostat import *
from .system_object.location_object.station_object.vantage_dmx_dali_gateway import *
from .system_object.location_object.vantage_ddg_color_load import *
from .system_object.location_object.vantage_dg_color_load import *
from .system_object.master import *
from .system_object.module import *
from .system_object.module_gen2 import *
from .system_object.power_profile import *
from .system_object.power_profile.dc_power_profile import *
from .system_object.power_profile.dc_power_profile.pwm_power_profile import *
from .system_object.station_bus import *
from .system_object.task import *
from .types import *
