name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Set up Python
      run: uv python install

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - run: echo "$PWD/.venv/bin" >> $GITHUB_PATH

    - name: Run black
      uses: psf/black@stable

    - name: Run ruff
      uses: astral-sh/ruff-action@v2

    - name: Run pyright
      uses: jakebailey/pyright-action@v2